-- MySQL Script generated by MySQL Workbench
-- Sat Dec  8 17:44:55 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pileta_api
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pileta_api` ;

-- -----------------------------------------------------
-- Schema pileta_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pileta_api` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `pileta_api` ;

-- -----------------------------------------------------
-- Table `pileta_api`.`variables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pileta_api`.`variables` ;

CREATE TABLE IF NOT EXISTS `pileta_api`.`variables` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `min` INT NOT NULL,
  `max` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pileta_api`.`devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pileta_api`.`devices` ;

CREATE TABLE IF NOT EXISTS `pileta_api`.`devices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `ip` VARCHAR(255) NOT NULL,
  `notes` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pileta_api`.`measurments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pileta_api`.`measurments` ;

CREATE TABLE IF NOT EXISTS `pileta_api`.`measurments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `variable_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `value` DOUBLE NOT NULL,
  `request_payload` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_measurments_devices_idx` (`device_id` ASC),
  INDEX `fk_measurments_variables1_idx` (`variable_id` ASC),
  CONSTRAINT `fk_measurments_devices`
    FOREIGN KEY (`device_id`)
    REFERENCES `pileta_api`.`devices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_measurments_variables1`
    FOREIGN KEY (`variable_id`)
    REFERENCES `pileta_api`.`variables` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
